# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b1f2bd0607651cccd56ee34b08283d0fc4ae815626618e047f0860d602a83c511a59320a4aa9dd49dfc4c931f08b28694db7ebbd710752351b059f563b2e975

test:
  secret_key_base: 0f7cfcc8d313684f01a419b567e789372008b446937d30c8d714777996dc0b0ef9ac3324eb5b3cffe0df27b240f5a6d2e9d9f0106e16418e866ea34c6fc16062

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
